version: '3.9'

services:
  db:
    container_name: database
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=douglas
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=marketplace
